flags:
  text:
    integer-simple: false
packages:
- '.'
- ../../Code/stack-ide/stack-ide
- ../../Code/stack-ide/stack-ide-api
- ../../Code/ide-backend/ide-backend
- ../../Code/ide-backend/ide-backend-rts
- ../../Code/ide-backend/ide-backend-server
- ../../Code/ide-backend/ide-backend-common
- ../gl-pal2
- ../Thop/modules/glfw-pal
extra-deps:
- fsnotify-0.1.0.3
- halive-0.1.0.5
- hfsevents-0.1.5
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
resolver: nightly-2015-06-28
